#' Compute and plot comparisons
#'
#' Plots raw data (bars for nominal, violing for continuous)
#' and their regression summaries (mean, 95% CI)
#'
#' @param data Tibble or data.frame. Raw data as generated
#'   by \code{import_data}.
#' @param stats Tibble or data.frame. Statistic comparisons
#'   as generated by \code{stat_test}.
#' @param vars Tibble or data.frame with variables of interest:
#' \describe{
#'   \item{label}{Facet name.}
#'   \item{name}{Y-axis name.}
#'   \item{var}{Variable in data name.}
#'   \item{y_min}{Minimum on y-axis.}
#'   \item{y_max}{Maximum on y-axis.}
#'   \item{type}{`"binomial"` or `"continuous"`}
#'   \item{stats_txt}{Text for statistics.}
#' }.
#' @param save Logical. Save the plot into `figures` folder?
#'   Defaults to `TRUE` which also creates `figures/` if it
#'   does not exist yet.
#'
#' @returns ggplot.
#'
#' @export
plot_comparisons <- function(
    data,
    stats,
    vars = NULL,
    save = TRUE) {
  # Use defaults if no specifications are present:
  if (rlang::is_empty(vars)) {
    vars <- tibble::tibble(
      label = c(
        "SuperAging",
        "Current PA",
        "Cognitive Composite",
        "Episodic Memory",
        "Global Cognition",
        "Instrumental ADLs",
        "Anxiety",
        "Depression"
      ),
      name = c(
        "",
        "",
        "Composite z-score",
        "Delayed Recall z-score",
        "MMSE (0-30)",
        "FAQ (0-30)",
        "GAI (0-20)",
        "GDS-15 (0-15)"
      ),
      var = c(
        "SA",
        "cPA",
        "Z_SA",
        "Delayed_recall_z",
        "MMSE",
        "FAQ",
        "GAI",
        "GDS15"
      ),
      y_max = c(1.05, 1.05, 2.75, 1.95, 30.8, 5, 17, 14),
      y_min = c(0, 0, -2.05, -2.45, 24.0, 0, 0, 0),
      type = c(rep("binomial", 2), rep("continuous", 6)),
      stats_txt = c(
        "X2(1) = 0.36, p = .551, V = 0.035",
        "X2(1) = 22.01, p < .001, V = 0.273",
        "W = 6995, p = .158, r = 0.082",
        "W = 9376, p = .013, r = 0.144",
        "W = 11736, p < .001, r = 0.371",
        "W = 5774, p < .001, r = 0.285",
        "W = 5413, p < .001, r = 0.237",
        "W = 4658, p < .001, r = 0.311"
      )
    )
  }
  # Re-code data:
  d0 <- data |> dplyr::mutate(
    SA = as.numeric(SA) - 1,
    cPA = as.numeric(cPA) - 1,
    mPA = dplyr::case_when(
      mPA == "COSACTIW" ~ "PAW",
      mPA == "NANOK" ~ "NC"
    )
  )
  # Keep only models of interest:
  res <- stats$unadjusted$mPA |>
    dplyr::filter(Outcome %in% vars$var & Effect == "total") |>
    dplyr::mutate(
      PAW_mean = as.numeric(stringr::str_extract(`mPA = COSACTIW`, "[-0-9.]+")),
      PAW_lower = as.numeric(stringr::str_extract(`mPA = COSACTIW`, "(?<=\\[)[-0-9.]+")),
      PAW_upper = as.numeric(stringr::str_extract(`mPA = COSACTIW`, "(?<=, )[-0-9.]+")),
      NC_mean = as.numeric(stringr::str_extract(`mPA = NANOK`, "[-0-9.]+")),
      NC_lower = as.numeric(stringr::str_extract(`mPA = NANOK`, "(?<=\\[)[-0-9.]+")),
      NC_upper = as.numeric(stringr::str_extract(`mPA = NANOK`, "(?<=, )[-0-9.]+")),
      p_txt = dplyr::if_else(
        `p value` == "< .001", `p value`, glue::glue("= {`p value`}")
      ),
      txt = dplyr::if_else(
        df > 1e5,
        glue::glue("OR = {Contrast}, p {p_txt}"),
        glue::glue("d = {Contrast}, p {p_txt}")
      )
    ) |>
    dplyr::select(
      Outcome, tidyselect::starts_with("PAW"), tidyselect::starts_with("NC"), txt
    ) |>
    tidyr::pivot_longer(
      cols = tidyselect::starts_with("PAW") | tidyselect::starts_with("NC"),
      names_to = c("mPA", "stat"),
      names_sep = "_"
    ) |>
    tidyr::pivot_wider(
      names_from = stat,
      values_from = value
    )
  # Do plotting:
  figs <- list()
  # Binomial variables:
  for (i in vars[vars$type == "binomial", ]$var) {
    figs[[i]] <- d0 |>
      tidyr::drop_na(tidyselect::all_of(i)) |>
      dplyr::group_by(mPA) |>
      dplyr::summarise(Proportion = mean(get(i)), .groups = "drop") |>
      dplyr::mutate(y = vars[vars$var == i, ]$label) |>
      ggplot2::ggplot() +
      ggplot2::aes(y = Proportion, x = mPA, fill = mPA) +
      ggplot2::geom_bar(stat = "identity", alpha = .33) +
      ggplot2::scale_y_continuous(
        limits = c(vars[vars$var == i, ]$y_min, vars[vars$var == i, ]$y_max)
      ) +
      ggplot2::geom_pointrange(
        data = res |> dplyr::filter(Outcome == i),
        ggplot2::aes(
          y = mean,
          ymin = lower,
          ymax = upper,
          colour = mPA
        ),
        size = .33
      ) +
      ggplot2::facet_wrap(~ y) +
      ggplot2::labs(x = NULL) +
      ggplot2::scale_fill_manual(values = c("green2", "deepskyblue")) +
      ggplot2::scale_colour_manual(values = c("green4", "navyblue")) +
      ggplot2::geom_text(
        data = vars[vars$var == i, ],
        ggplot2::aes(x = 1.5, y = y_max, label = stats_txt),
        inherit.aes = FALSE,
        size = 2.83
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        panel.grid = ggplot2::element_blank(),
        legend.position = "none"
      )
  }
  # Continuous variables:
  for (i in vars[vars$type == "continuous", ]$var) {
    figs[[i]] <- d0 |>
      dplyr::rename(y_val = i) |>
      dplyr::mutate(y_nam = vars[vars$var == i, ]$label) |>
      ggplot2::ggplot() +
      ggplot2::aes(x = mPA, fill = mPA, y = y_val) +
      ggplot2::geom_violin(
        position = ggplot2::position_dodge(0.5),
        alpha = .33,
        colour = NA
      ) +
      ggplot2::geom_pointrange(
        data = res |> dplyr::filter(Outcome == i),
        ggplot2::aes(
          y = mean,
          ymin = lower,
          ymax = upper
        ),
        size = .33
      ) +
      ggplot2::facet_wrap(~ y_nam) +
      ggplot2::labs(y = vars[vars$var == i, ]$name, x = NULL) +
      ggplot2::scale_fill_manual(values = c("green2", "deepskyblue")) +
      ggplot2::scale_colour_manual(values = c("green4", "navyblue")) +
      ggplot2::scale_y_continuous(
        limits = c(vars[vars$var == i, ]$y_min, vars[vars$var == i, ]$y_max)
      ) +
      ggplot2::geom_text(
        data = vars[vars$var == i, ],
        ggplot2::aes(x = 1.5, y = y_max, label = stats_txt),
        inherit.aes = FALSE,
        size = 2.83
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        panel.grid = ggplot2::element_blank(),
        legend.position = "none"
      )
  }
  # Return it:
  plt <- ggpubr::ggarrange(
    figs$SA, figs$Z_SA,
    figs$Delayed_recall_z, figs$cPA,
    figs$MMSE, figs$FAQ,
    figs$GAI, figs$GDS15,
    ncol = 2,
    nrow = 4
  )
  # Save it:
  if (save) {
    if (!dir.exists("figures")) {
      dir.create("figures")
    }
    ggplot2::ggsave(
      plot = plt,
      filename = here::here("figures", "selected_comparisons.jpg"),
      dpi = 300,
      width = 8.73,
      height = 8.69
    )
  }
  plt
}
