#' Prepare a table with single analysis
#'
#' Given results table, prepares an APA
#' style table with results for the analysis
#' of PAW vs. NC contrasts in regressions.
#'
#' @param tab Tibble. Table generated by \code{stat_test}.
#' @param gcomp Logical. Indicates whether the
#'   results come from g-computation (`TRUE`) or
#'   not (`FALSE`, default).
#' @param title Character.Specifies the table title.
#'   Will be converted to HTML format. Defaults to `""`.
#'
#' @returns Formatted {gt} table.
#'
#' @export
table_single <- function(tab, gcomp = FALSE, title = "") {
  # Preprocess the table:
  t0 <- tab |>
    dplyr::filter(Effect == "total" & Analysis != "0") |>
    dplyr::select(
      Outcome, tidyselect::starts_with("mPA"), Contrast, Statistic, df,
      `p value`, sig_FDR, residual_check_p, residual_check_sig, Analysis
    ) |>
    dplyr::mutate(
      Analysis = dplyr::case_when(
        Analysis == 1 ~ "SuperAging Correlates",
        Analysis == 2 ~ "SuperAging Components"
      ),
      Outcome = factor(
        dplyr::recode(
          Outcome,
          GAI = "GAI",
          GDS15 = "GDS-15",
          FAQ = "FAQ",
          Z_SA = "Cognition CS",
          Anx = "Anxiety risk",
          Depr = "Depression risk",
          cPA = "cPA",
          SA = "SA",
          Delayed_recall_z = "Memory (delayed recall)",
          TMT_B_z = "TMT-B",
          BNT_30_z = "BNT-30",
          VF_Animals_z = "Verbal Fluency (animals)"
        ),
        levels = c(
          "GAI",
          "GDS-15",
          "FAQ",
          "Cognition CS",
          "Anxiety risk",
          "Depression risk",
          "cPA",
          "SA",
          "Memory (delayed recall)",
          "TMT-B",
          "BNT-30",
          "Verbal Fluency (animals)"
        ),
        ordered = TRUE
      ),
      df = dplyr::if_else(df == Inf, "", as.character(df))
    ) |>
    dplyr::arrange(Outcome)
  # Prepare the note:
  note <- "*Note.* GAI = Geriatric Anxiety Inventory; GDS-15 = Geriatric Depression Inventory;
  FAQ = Functional Activities Questionnaire; CS = composite score;  cPA = currently physically
  active; SA = SuperAger; TMT-B = Trail Making Test, part B; BNT-30 = Boston Naming Test; PAW =
  physically active women in midlife according to WHO recommendations; NC = normal control group;
  \\* = statistically significant difference after adjustment for 5% False Discovery Rate within an
  analysis (SuperAging Correlates and SuperAging Components comprise two distinct analyses)"
  if (gcomp) {
    note <- glue::glue(
      "{note}."
    )
  } else {
    note <- glue::glue(
      "{note}; ! = statistically significant difference between simulated quantile residuals
      and uniform distribution."
    )
  }
  if (gcomp) {
    t0 <- t0 |>
      dplyr::select(-tidyselect::starts_with("residual"), -Statistic, -df)
  }
  # Print the table:
  tab <- t0 |>
    gt_apa_table(grp = "Analysis", tit = title) |>
    gt::tab_spanner(
      label = "Distribution check",
      columns = tidyselect::starts_with("residual"),
      gather = FALSE
    ) |>
    gt::cols_label(
      Outcome ~ "Presumed outcome",
      `mPA = COSACTIW` ~ "PAW",
      `mPA = NANOK` ~ "NC",
      tidyselect::contains("sig") ~ "sig.",
      tidyselect::ends_with("_p") ~ "p value"
    ) |>
    gt::tab_footnote(
      footnote = "Conditional mean differences (d) for continuous presumed outcomes: GAI, GDS-15, FAQ, cognition CS, memory, TMT-B, BNT-30, verbal fluency; conditional odds ratios (OR) for binary presumed outcomes: Anxiety risk, depression risk, cPA, SA.",
      locations = gt::cells_column_labels(Contrast)
    ) |>
    gt::tab_source_note(gt::md(note))
  # Return:
  if (gcomp) {
    tab
  } else {
    tab |> gt::tab_footnote(
      footnote = gt::html("t-value continuous presumed outcomes; &chi;<sup>2</sup> for binary presumed outcomes."),
      locations = gt::cells_column_labels(Statistic)
    )
  }
}
